name: Daily Crawler

on:
  schedule:
    - cron: "0 0 * * *" # 台灣時間 8:00
    - cron: "0 4 * * *" # 台灣時間 12:00
    - cron: "0 7 * * *" # 台灣時間 15:00
  workflow_dispatch:

permissions:
  contents: write # <--- 這行很重要，讓 bot 有權限 push 回 repo

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run crawler
        run: python sync104_jobs.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          CRAWLER_URL: ${{secrets.CRAWLER_URL}}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPICS_OTHER: ${{secrets.TELEGRAM_TOPICS_OTHER}}
          TELEGRAM_TOPICS_ERROR: ${{secrets.TELEGRAM_TOPICS_ERROR}}
          TELEGRAM_TOPICS_SHOPEE: ${{secrets.TELEGRAM_TOPICS_SHOPEE}}
          TELEGRAM_TOPICS_SHINYWEB: ${{secrets.TELEGRAM_TOPICS_SHINYWEB}}
          TELEGRAM_TOPICS_YAHOO: ${{secrets.TELEGRAM_TOPICS_YAHOO}}
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/jobs.json
          git commit -m "chore: update jobs.json"
          git push
