name: Daily Crawler

on:
  schedule:
    - cron: "0 0 * * *" # UTC 凌晨 0 點，台灣時間應該是早上 8 點 (UTC+8)
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run crawler
        run: python sync104_jobs.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          CRAWLER_URL: ${{secrets.CRAWLER_URL}}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPICS_OTHER=${{secrets.TELEGRAM_TOPICS_OTHER}}
          TELEGRAM_TOPICS_ERROR=${{secrets.TELEGRAM_TOPICS_ERROR}}
          TELEGRAM_TOPICS_SHOPEE=${{secrets.TELEGRAM_TOPICS_SHOPEE}}
          TELEGRAM_TOPICS_SHINYWEB=${{secrets.TELEGRAM_TOPICS_SHINYWEB}}
          TELEGRAM_TOPICS_YAHOO=${{secrets.TELEGRAM_TOPICS_YAHOO}}